travis:
  secure:
    BINSTAR_TOKEN: qvgoScbTJZjOnZjxDzMsXoDzk64+B48FFT09NbSJqLbIYu9GqwB8DS2kmzoXlVsBMN1mpF+oUh5Ltzg828BuP3ysbI1ylNZVk3WdM9UPMS8mZ8LhuKyxNnd2MhQYYZAHFdTNaGu8JLU3BjfMgQVPhpqgsmUYk9eV+qM57TdeI7dXlIlyautzTcwSEdeatTx7S9M21cUGFb99m3Hp9kZ89h+7xKRvHtKhT+o1DpxcgOHYefsVQ+p14csHQqtRnenbz6FnWnHNNr7GF5NjWMUTtoyM+QVmAnd+/3k4vqRxGug10MtM6XvaKOq4jk15FlL7ebZcOLNRwrg5y8jsSPNY8y0TMw9xjrpmx+s1x48drDeyxgjAFUIIbTVplAxHGllOPFw16nWw+gxE1wbCy6yIIOgdwQN6ahCiUgZ6luOSFnZLStscuPflt+JHdX2xITck1T64FwWHAx4nChYYENoN05+bVccTSTtQW8m7KUGJ106JiF+YJLqZNNc6ev2J3HDw2CgIS2/jFwbznW/rKoPnTvvuJnwQpxgbZ3tN+njCtLqxdv14OtUniafGSJhGHBxKhmuY3RrNe5P+veRmt7/oYcdAxvxqRHZKmVYaKB0BQQ3z9mGTNnWandc3eX03zGUzDQPgDIu64phgSm/JqCGeb/xOc5/wCLu0dYAUqbYs1Cs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
